### ISSUE TITLE
Удаление файлов

### ISSUE THREAD

**Issue by serSok** [LowerDeez/ok-images#1]
1. В админ панели загрузили файл - поле обязательное к заполнению
2. Сохранили
3. Отметили чекБокс "очистить" - сохранили
4. в админике проругались что поле обязательно
5. Обновили страницу - "нет файла накоторый ссылается объект"

Проверял в инлайнере

**Comment by serSok** [comment]
Обновили страницу - "нет файла накоторый ссылается объект" - файла на диске нет, а ссылки на него существеют

**Comment by LowerDeez** [comment]
Поправил сохранение
